<x-shape::icon.shape-checked />
<x-shape::icon.shape-indeterminate />
<x-shape::icon.shape-prev />
<x-shape::icon.shape-next />
<x-shape::icon.shape-expand />
<x-shape::icon.shape-close />
<x-shape::icon.shape-success />
<x-shape::icon.shape-danger />
<x-shape::icon.shape-warning />
<x-shape::icon.shape-info />
<x-shape::icon.shape-trend-up />
<x-shape::icon.shape-trend-down />
<x-shape::icon.shape-trend-flat />
<x-shape::icon.shape-loading />
