<?php

declare(strict_types=1);

namespace Onelegstudios\Shape\Console\Commands;

use Illuminate\Console\Command;
use InvalidArgumentException;
use Onelegstudios\Shape\FoldSafety;
use Onelegstudios\Shape\IconSlots;
use Onelegstudios\Shape\Registry;
use SplFileInfo;
use Symfony\Component\Finder\Finder;

/**
 * Lint components for the one mistake that costs the fold and says nothing.
 *
 * A component that reads global state still renders. It renders correctly, in
 * development, for the developer who wrote it. What it stops doing is folding —
 * or worse, it folds and serves one visitor's session to everybody. Neither
 * failure has a stack trace, which is why this is a command rather than a
 * paragraph in the documentation.
 *
 * It runs over the ejected components in the application by default, because
 * that is where the rule is easiest to break: the file is in `resources/views`
 * now, it looks like every other Blade file in the project, and nothing about it
 * says the compiler is going to pre-render it.
 *
 * Slot coverage is here for the same reason and is otherwise unrelated. Once an
 * application has replaced Shape's icons with a set of its own, a slot it missed
 * does not fail — it resolves to the packaged Heroicon and draws perfectly, in
 * the wrong set, on a page that is now wearing two. Nothing renders red, so
 * something has to say it out loud.
 *
 * Three states there, not two: a slot **generated** from the set, a slot
 * **packaged** by Shape because no set is asked to fill it, and a slot
 * **missing** and drawing a Heroicon nobody chose. Only the last is a finding.
 */
class DoctorCommand extends Command
{
    /**
     * The command signature.
     */
    protected $signature = 'shape:doctor
        {--path=* : Directories to lint instead of the ejected components}
        {--package : Lint the components this package ships}';

    /**
     * The command description.
     */
    protected $description = 'Check Shape components for the global state that costs them their fold.';

    /**
     * Execute the console command.
     */
    public function handle(Registry $registry, FoldSafety $safety): int
    {
        $paths = $this->paths($registry);

        if ($paths === []) {
            $this->components->info('No components to check. Eject one with `shape:eject`, or pass --path.');

            return self::SUCCESS;
        }

        $offences = 0;
        $checked = 0;

        foreach ($paths as $path) {
            $this->components->info("Checking {$path}");

            foreach ($this->components($path) as $file) {
                $checked++;
                $offences += $this->check($safety, $file, $path);
            }
        }

        [$missing, $undeclared] = $this->coverage($registry);

        $this->newLine();

        if ($offences === 0 && $missing === 0 && $undeclared === 0) {
            $this->components->info("{$checked} component(s) checked, and every one of them folds cleanly.");

            return self::SUCCESS;
        }

        if ($offences > 0) {
            $this->components->error("{$offences} problem(s) in {$checked} component(s).");
            $this->line('  A folded component is rendered once, while Blade compiles. Anything above');
            $this->line('  belongs at the call site, or inside an @unblaze block that cuts a hole in');
            $this->line('  the fold on purpose — which is what `error.blade.php` does, and why.');
        }

        if ($missing > 0) {
            $this->components->error("{$missing} slot(s) Shape resolves for you are not in your set.");
            $this->line('  Each one falls back to the icon this package ships, so those components');
            $this->line('  render in Heroicons while the rest of the page renders in yours. Generate');
            $this->line('  them with `shape:icon --replace`, and if a slot has no drawing under it,');
            $this->line('  say which of your set\'s drawings fills it in `shape.icon_sets.*.slots`.');
        }

        if ($undeclared > 0) {
            $this->components->error("{$undeclared} slot(s) your components draw are not declared.");
            $this->line('  A slot missing from `shape.icon_slots` is generated by nothing and');
            $this->line('  checked by nothing, so it goes on resolving to the icon this package');
            $this->line('  ships however many sets you replace. Declare it, and give every set an');
            $this->line('  entry for it.');
        }

        return self::FAILURE;
    }

    /**
     * Report how much of what Shape resolves for you the ejected set covers.
     *
     * The slots are declared, in `shape.icon_slots`; whether each is covered is
     * read out of the directory those names resolve from first. The check is
     * silent when nothing has been ejected into that directory — an application
     * on the packaged icons is not partially covered, it is covered.
     *
     * Three states, and only the third is a finding:
     *
     * - **generated** — the ejected directory holds the slot, drawn from a set.
     * - **packaged** — Shape draws this one itself and no set has to fill it.
     *   `shape-loading` is the only one, and reporting it as missing would be
     *   telling somebody to fix the answer they already have.
     * - **missing** — nothing fills it, so the component that resolves it goes
     *   on drawing a Heroicon on a page that is otherwise not in Heroicons.
     *
     * Anything else in the directory gets a line and never a finding: the three
     * examples this package ships, if they were ever generated, and whatever the
     * application has generated for itself. `--replace` does not touch either,
     * correctly — they are not Shape's — but they are the drawings it will not
     * keep level with the rest, so they are worth naming.
     *
     * @return array{0: int, 1: int} The slots missing, and the slots drawn but never declared.
     */
    protected function coverage(Registry $registry): array
    {
        $path = config('shape.components_path');

        if (! is_string($path) || ! is_dir($directory = rtrim($path, '/').'/icon')) {
            return [0, 0];
        }

        try {
            $slots = IconSlots::fromConfig();
        } catch (InvalidArgumentException $e) {
            $this->components->error($e->getMessage());

            return [1, 0];
        }

        $declared = $slots->names();
        $ejected = fn (string $name): bool => is_file($directory.'/'.$name.'.blade.php');

        $present = array_values(array_filter($declared, $ejected));

        if ($present === []) {
            return [0, 0];
        }

        $undeclared = array_values(array_diff($registry->icons(), $declared));

        $missing = [];
        $packaged = [];

        foreach ($declared as $name) {
            if ($ejected($name)) {
                continue;
            }

            if ($slots->isPackaged($name)) {
                $packaged[] = $name;

                continue;
            }

            $missing[] = $name;
        }

        $this->components->twoColumnDetail(
            'icon set',
            $this->attribution($directory, $present).', '.count($present).' of '.count($declared).' slots',
        );

        foreach ($packaged as $name) {
            $this->components->twoColumnDetail(
                "  {$name}",
                '<fg=gray>packaged — Shape draws this one, your set need not</>',
            );
        }

        foreach ($missing as $name) {
            $this->components->twoColumnDetail(
                "  {$name}",
                '<fg=red>missing</> <fg=gray>— falls back to Heroicons</>',
            );
        }

        foreach ($undeclared as $name) {
            $this->components->twoColumnDetail(
                "  {$name}",
                '<fg=red>drawn by a component, undeclared</>',
            );
        }

        $this->extras($directory, $declared);

        return [count($missing), count($undeclared)];
    }

    /**
     * Say what else is in the directory, without calling it a problem.
     *
     * Icons outside the slot list: ones the application generated for itself,
     * and the three examples this package ships if they were ever ejected.
     * `--replace` does not touch either and should not — neither is Shape's to
     * keep level with your set. But they sit in the same directory, drawn by
     * whichever set was pointed at when they were generated, and a reader
     * looking at a coverage report should be told they are there rather than
     * left to infer it from a count that excludes them.
     *
     * @param  list<string>  $declared
     */
    protected function extras(string $directory, array $declared): void
    {
        $extras = [];

        foreach (glob($directory.'/*.blade.php') ?: [] as $file) {
            $name = basename($file, '.blade.php');

            if ($name !== 'index' && ! in_array($name, $declared, true)) {
                $extras[] = $name;
            }
        }

        if ($extras === []) {
            return;
        }

        sort($extras);

        $this->components->twoColumnDetail(
            '  outside the slots',
            '<fg=gray>'.implode(', ', $extras).'</>',
        );
    }

    /**
     * Which set the ejected icons came from, as far as they will say.
     *
     * Every generated icon carries its set's notice verbatim, so this is a fact
     * about the files rather than a guess about them. Two answers instead of one
     * is worth printing on its own: a directory holding icons from two sets is
     * the mistake this whole check is looking for, arrived at from the other
     * direction.
     *
     * @param  list<string>  $present
     */
    protected function attribution(string $directory, array $present): string
    {
        $sets = config('shape.icon_sets');
        $found = [];

        foreach ($present as $name) {
            $source = (string) file_get_contents($directory.'/'.$name.'.blade.php');

            foreach (is_array($sets) ? $sets : [] as $set => $definition) {
                $notice = is_array($definition) ? ($definition['notice'] ?? null) : null;

                if (is_string($notice) && $notice !== '' && str_contains($source, $notice)) {
                    $found[(string) $set] = true;
                }
            }
        }

        return $found === [] ? 'unattributed' : implode(' and ', array_keys($found));
    }

    /**
     * Report on one component, and return how many problems it has.
     */
    protected function check(FoldSafety $safety, SplFileInfo $file, string $root): int
    {
        $name = str_replace($root.'/', '', $file->getPathname());
        $source = (string) file_get_contents($file->getPathname());

        if (! $safety->declaresStrategy($source)) {
            $this->components->twoColumnDetail(
                "  {$name}",
                '<fg=yellow>no @blaze annotation</>',
            );

            return 1;
        }

        $found = $safety->inspect($source);

        if ($found === []) {
            if ($this->output->isVerbose()) {
                $this->components->twoColumnDetail("  {$name}", '<fg=green>ok</>');
            }

            return 0;
        }

        foreach ($found as $offence) {
            $this->components->twoColumnDetail(
                "  {$name}:{$offence['line']} <fg=red>{$offence['pattern']}</>",
                "<fg=gray>{$offence['hint']}, resolved once at compile time</>",
            );
        }

        return count($found);
    }

    /**
     * The directories to lint.
     *
     * @return list<string>
     */
    protected function paths(Registry $registry): array
    {
        /** @var list<string> $paths */
        $paths = (array) $this->option('path');

        if ($this->option('package')) {
            $paths[] = $registry->views();
        }

        if ($paths === []) {
            $ejected = config('shape.components_path');

            if (is_string($ejected)) {
                $paths[] = $ejected;
            }
        }

        return array_values(array_filter(array_map(
            fn (string $path): string => rtrim($path, '/'),
            $paths,
        ), 'is_dir'));
    }

    /**
     * The Blade files under a directory.
     *
     * @return iterable<SplFileInfo>
     */
    protected function components(string $path): iterable
    {
        return Finder::create()->files()->in($path)->name('*.blade.php')->sortByName();
    }
}
